use_gpu: True
device: 0
outdir: learn_from_scratch
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  total_round_num: 100
  client_num: 2000
  online_aggr: True
  share_local_model: True
  sample_client_rate: 0.01
data:
  root: data/
  type: HFLNetflix
dataloader:
  batch_size: 32
  type: mf
model:
  type: HMFNet
  hidden: 10
train:
  local_update_steps: 50
  optimizer:
    lr: 1.
criterion:
  type: MSELoss
trainer:
  type: mftrainer
eval:
  freq: 100
  metrics: []