use_gpu: True
device: 3
outdir: rs_netflix_avg
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  total_round_num: 100
  client_num: 200
  online_aggr: True
  share_local_model: True
  sample_client_rate: 0.01
data:
  root: data/
  type: HFLNetflix
  subsample: 0.001
dataloader:
  batch_size: 32
  type: mf
model:
  type: HMFNet
  hidden: 10
train:
  local_update_steps: 50
  optimizer:
    lr: 1.
criterion:
  type: MSELoss
trainer:
  type: mftrainer
eval:
  freq: 100
  metrics: []
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False
hpo:
  scheduler: rs
  num_workers: 0
  init_cand_num: 10
  ss: 'scripts/hpo_exp_scripts/usability/netflix/ss.yaml'
  sha:
    budgets: [ 50, 50 ]
    elim_rate: 3
    iter: 50
  metric: 'client_summarized_weighted_avg.val_avg_loss'
  working_folder: rs_netflix_avg
