use_gpu: True
device: 3
outdir: rs_wrap_netflix_avg
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  total_round_num: 100
  client_num: 200
  online_aggr: True
  share_local_model: True
  use_diff: True
  sample_client_rate: 1.0
data:
  root: data/
  subsample: 0.05
  type: HFLNetflix
dataloader:
  batch_size: 32
  type: mf
model:
  type: HMFNet
  hidden: 10
train:
  local_update_steps: 50
  optimizer:
    lr: 1.
criterion:
  type: MSELoss
trainer:
  type: mftrainer
eval:
  freq: 1
  metrics: []
  split: ['test', 'val', 'train']
  best_res_update_round_wise_key: val_avg_loss
  count_flops: False
hpo:
  scheduler: wrap_rs
  num_workers: 0
  init_cand_num: 100
  ss: 'scripts/hpo_exp_scripts/usability/netflix/ss.yaml'
  sha:
    budgets: [ 50, 50 ]
    elim_rate: 3
    iter: 50
  fedex:
    sched: 'aggressive'
    use: True
    diff: False
    eta0: -1.0
    gamma: 0.0
    wrapper:
      arm: 27
  metric: 'client_summarized_weighted_avg.val_avg_loss'
  working_folder: rs_wrap_netflix_avg
