use_gpu: True
device: 0
seed: 12345
federate:
  mode: standalone
  client_num: 5
  total_round_num: 300
data:
  root: data/
  type: 'CIFAR10@torchvision'
  splits: [0.9, 0.1, 0.0]
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]]
  args: [{'download': True}]
  splitter: 'lda'
  splitter_args: [{'alpha': 1.0}]
dataloader:
  batch_size: 64
model:
  type: convnet2
  hidden: 2048
  out_channels: 10
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: val_loss
matching:
  use: True
  method: pad
  round: 50
