name: Full Testing

on: [push, pull_request]

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9']
        torch-version: [1.10.1]
        include:
          - torch-version: 1.12.0
            torchvision-version: 0.11.2
            torchaudio-version: 0.10.

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          pip install numpy typing-extensions dataclasses
          pip install torch==${{ matrix.torch-version}}+cpu torchvision==${{ matrix.torchvision-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      
      - name: Install develop version of FS
        run: |
          pip install -e . [dev]
          
      - name: Install application dependenies
        run: |
          pip install numpy # To be fixed.

      - name: Generate coverage report
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
