name: pre-commit

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pre-commit
        pre-commit install
    - name: Launch pre-commit
      run: |
        pre-commit run --all-files > pre-commit.log
        cat pre-commit.log
    - name: Check failure
      if: ${{grep -q "Failed" pre-commit.log > 0}}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Pre-commit check failed!')
